API_CURRENT_VERSION = "1"
API_ENTRYPOINT = f"/api/v{API_CURRENT_VERSION}"
DEBUG = True # Don't commit to maser branch when DEBUG is set to True!
ALPHANUMERIC = "0123456789qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"
API_TOKEN_SIZE = 64